import { Game, GameConsoleDetails } from "../types/games";

export const MOCK_GAMES: Game[] = [
    {
        _id: '1',
        title: 'Cyberpunk 2077',
        sortTitle: 'Cyberpunk 2077',
        series: 'Cyberpunk',
        image: 'https://unsplash.com', // Replace with real asset/API links
        genre: 'Open World RPG',
        interest: 'must-play',
        progress: 'playing',
        progressDescription: 'Currently playing',
        addedDate: new Date('2023-01-15'),
        modifiedDate: new Date('2023-01-20'),
        onList: true,
    },
    {
        _id: '2',
        title: 'Elden Ring: Shadow of the Erdtree',
        sortTitle: 'Elden Ring: Shadow of the Erdtree',
        series: 'Dark Souls',
        image: 'https://unsplash.com',
        genre: 'Action RPG',
        interest: 'very-interested',
        progress: 'backlog',
        progressDescription: 'In backlog',
        addedDate: new Date('2023-01-15'),
        modifiedDate: new Date('2023-01-20'),
        onList: true,
    },
    {
        _id: '3',
        title: 'Hades II',
        sortTitle: 'Hades II',
        series: 'Hades',
        image: 'https://unsplash.com',
        genre: 'Action Roguelike',
        interest: 'must-play',
        progress: 'wishlist',
        progressDescription: 'On Wishlist',
        addedDate: new Date('2023-01-15'),
        modifiedDate: new Date('2023-01-20'),
        onList: false,
    },
    {
        _id: '4',
        title: 'The Witcher 3: Wild Hunt',
        sortTitle: 'Witcher 3: Wild Hunt',
        series: 'The Witcher',
        image: 'https://unsplash.com',
        genre: 'Open World RPG',
        interest: 'na',
        progress: 'playing',
        progressDescription: 'Currently playing',
        addedDate: new Date('2023-01-15'),
        modifiedDate: new Date('2023-01-20'),
        onList: false,
    },
    {
        _id: '5',
        title: 'Baldur\'s Gate 3',
        sortTitle: 'Baldur\'s Gate 3',
        series: 'Baldur\'s Gate',
        image: 'https://unsplash.com',
        genre: 'RPG',
        interest: 'not-interested',
        progress: 'playing',
        progressDescription: 'Currently playing',
        addedDate: new Date('2023-01-15'),
        modifiedDate: new Date('2023-01-20'),
        onList: false,
    },
];

export const MockGameDetails: GameConsoleDetails[] = [
    {
        _id: '1',
        console: 'ps5',
        ownedState: 'digital',
        gameId: '1',
        releaseYear: 2023,
    },
    {
        _id: '2',
        console: 'ps5',
        ownedState: 'physical',
        gameId: '1',
        releaseYear: 2023,
    },
    {
        _id: '3',
        console: 'ps5',
        ownedState: 'wishlist',
        gameId: '2',
        releaseYear: 2023,
    },
    {
        _id: '4',
        console: 'ps5',
        ownedState: 'emulator',
        gameId: '3',
        releaseYear: 2022,
    },
    {
        _id: '5',
        console: 'switch',
        ownedState: 'digital',
        gameId: '4',
        releaseYear: 2023,
    },
    {
        _id: '6',
        console: 'switch',
        ownedState: 'physical',
        gameId: '5',
        releaseYear: 2023,
    }
] 